#!/usr/bin/env python3
"""Gzip web/index.html into src/web_assets.h as a const byte array.

The Photon 1 has 128 KB of application flash and no filesystem, so the config
page ships inside the firmware image. Gzipping first typically cuts it ~4x.

Run before every `particle compile`:  python3 tools/build_web_assets.py
"""

import gzip
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "web" / "index.html"
DST = ROOT / "src" / "web_assets.h"

# Flash budget guard. Raised from 14 KB once Phase 0 showed the real image was
# less than half the estimate -- with ~55 KB of flash still free, 14 KB was
# tighter than anything justified. Still a guard, not a target: if the page
# doubles again, that is worth noticing rather than silently absorbing.
MAX_GZIP_BYTES = 20 * 1024


def main() -> int:
    if not SRC.exists():
        print(f"error: {SRC} not found", file=sys.stderr)
        return 1

    raw = SRC.read_bytes()
    # mtime=0 keeps the output byte-identical across runs so unchanged pages
    # don't show up as spurious diffs.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)

    if len(packed) > MAX_GZIP_BYTES:
        print(
            f"error: gzipped page is {len(packed)} bytes, over the "
            f"{MAX_GZIP_BYTES} byte budget",
            file=sys.stderr,
        )
        return 1

    lines = [
        "// Generated by tools/build_web_assets.py -- do not edit.",
        "// Source: web/index.html",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"// {len(raw)} bytes raw -> {len(packed)} bytes gzipped",
        f"const uint32_t WEB_INDEX_GZ_LEN = {len(packed)};",
        "const uint8_t WEB_INDEX_GZ[] = {",
    ]
    for i in range(0, len(packed), 16):
        chunk = packed[i : i + 16]
        lines.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    lines.append("")

    DST.write_text("\n".join(lines))

    pct = 100.0 * len(packed) / len(raw)
    print(
        f"web/index.html: {len(raw)} bytes -> {len(packed)} bytes gzipped "
        f"({pct:.1f}%), {MAX_GZIP_BYTES - len(packed)} bytes under budget"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
