// Generates cross-validation vectors for the timezone pipeline.
//
// The browser derives a POSIX rule from Intl; the device parses that rule with
// its own C++ code. Those two halves have to agree, and nothing else in the
// test suite proves it. This script emits, for a spread of zones:
//
//   zone <TAB> posix-rule <TAB> epoch:expected_west_offset_seconds,...
//
// where the expected offsets come from Intl (the authority) rather than from
// our own parser. tests/tzvec_test.cpp then checks the C++ side reproduces them.
//
//   node tools/gen_tz_vectors.mjs > tests/tz_vectors.txt

import { readFileSync } from 'fs';

// Pull the derivation functions straight out of the page so the vectors always
// describe the code that actually ships.
const html = readFileSync(new URL('../web/index.html', import.meta.url), 'utf8');
const js = html.split('<script>')[1].split('</script>')[0];
const slice = js.slice(js.indexOf('function offsetMinutes'), js.indexOf('function refreshTzRule'));
eval(slice + '\nglobalThis.posixTz = posixTz; globalThis.offsetMinutes = offsetMinutes;');

const ZONES = [
  // North America
  'America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles',
  'America/Phoenix', 'America/Anchorage', 'Pacific/Honolulu', 'America/Halifax',
  'America/St_Johns',                       // half-hour offset with DST
  // Europe / Africa
  'Europe/London', 'Europe/Dublin', 'Europe/Berlin', 'Europe/Paris', 'Europe/Lisbon',
  'Europe/Athens', 'Europe/Moscow', 'Africa/Cairo', 'Africa/Nairobi',
  'Africa/Johannesburg', 'Atlantic/Azores',
  // Asia
  'Asia/Kolkata', 'Asia/Kathmandu',         // :45 offset
  'Asia/Tokyo', 'Asia/Shanghai', 'Asia/Tehran', 'Asia/Jerusalem', 'Asia/Dubai',
  // Southern hemisphere DST
  'Australia/Sydney', 'Australia/Adelaide', 'Australia/Perth',
  'Australia/Lord_Howe',                    // 30-minute DST shift
  'Pacific/Auckland', 'Pacific/Chatham',     // :45 offset with DST
  'America/Santiago', 'America/Sao_Paulo', 'America/Asuncion',
  'Antarctica/Troll',                        // 0 <-> +2 DST
  'UTC',
];

const YEAR = new Date().getUTCFullYear();
const out = [];

for (const zone of ZONES) {
  let rule;
  try { rule = posixTz(zone); } catch (e) { continue; }

  const samples = [];
  const push = (ms) => {
    const epoch = Math.floor(ms / 1000);
    // Intl reports east-of-UTC minutes; POSIX stores west-positive seconds.
    samples.push(epoch + ':' + (-offsetMinutes(zone, new Date(ms)) * 60));
  };

  // Twice a month, away from the small hours where transitions happen.
  for (let mo = 0; mo < 12; mo++) {
    push(Date.UTC(YEAR, mo, 1, 12));
    push(Date.UTC(YEAR, mo, 15, 12));
  }

  // Straddle each transition, where an off-by-one rule actually shows up.
  for (let mo = 0; mo < 12; mo++) {
    const a = Date.UTC(YEAR, mo, 1), b = Date.UTC(YEAR, mo + 1, 1);
    let lo = a, hi = b;
    if (offsetMinutes(zone, new Date(lo)) === offsetMinutes(zone, new Date(hi))) continue;
    const loOff = offsetMinutes(zone, new Date(lo));
    while (hi - lo > 60000) {
      const mid = Math.floor((lo + hi) / 2);
      if (offsetMinutes(zone, new Date(mid)) === loOff) lo = mid; else hi = mid;
    }
    push(hi - 90 * 60000);   // 90 min before
    push(hi - 60 * 1000);    // 1 min before
    push(hi + 60 * 1000);    // 1 min after
    push(hi + 90 * 60000);   // 90 min after
  }

  out.push(zone + '\t' + rule + '\t' + samples.join(','));
}

process.stdout.write('# generated by tools/gen_tz_vectors.mjs for ' + YEAR + '\n');
process.stdout.write(out.join('\n') + '\n');
