#!/usr/bin/env python3
"""Generates independent sunrise/sunset reference vectors using `astral`.

Validating our NOAA implementation against our own maths would prove nothing,
so the expected values come from astral -- a separate, widely used
implementation of the same NOAA method.

An earlier version of this used api.sunrise-sunset.org. That service disagrees
with both astral and this firmware by about 70 seconds in a consistent
direction (it reports longer days), which reads as a different horizon constant.
Where two references disagree, the one that matches the published NOAA method is
the one to test against -- but the discrepancy is worth knowing about, so
tests/solar_vectors_sunrisesunset.txt keeps the other set for comparison.

    pip install astral
    python3 tools/gen_solar_vectors.py > tests/solar_vectors.txt

Output: name <TAB> lat <TAB> lon <TAB> YYYY-MM-DD <TAB> rise_epoch <TAB> set_epoch
"""

import datetime
import sys

from astral import sun

LOCATIONS = [
    ("Durham", 35.9940, -78.8986),
    ("Anchorage", 61.2181, -149.9003),
    ("Reykjavik", 64.1466, -21.9426),
    ("Quito", -0.1807, -78.4678),
    ("Singapore", 1.3521, 103.8198),
    ("Sydney", -33.8688, 151.2093),
    ("Ushuaia", -54.8019, -68.3030),
    ("Nairobi", -1.2921, 36.8219),
    ("Tromso", 69.6492, 18.9553),
]

DATES = ["2026-01-15", "2026-03-20", "2026-05-01", "2026-06-21",
         "2026-08-16", "2026-09-22", "2026-11-01", "2026-12-21"]

UTC = datetime.timezone.utc


def main() -> int:
    print("# independent reference generated by tools/gen_solar_vectors.py (astral)")
    for name, lat, lon in LOCATIONS:
        obs = sun.Observer(latitude=lat, longitude=lon, elevation=0)
        for ds in DATES:
            d = datetime.date.fromisoformat(ds)

            # Both sides must describe the SAME solar day, or the comparison is
            # meaningless. The firmware defines a solar day as the rise and set
            # bracketing solar noon of the given UTC date; astral returns
            # whichever event happens to fall inside that UTC date. Those differ
            # by a whole day at far-eastern and far-western longitudes -- Sydney
            # and Singapore came out exactly 86400 s apart before this.
            #
            # So: anchor on solar noon and take the rise just before it and the
            # set just after, searching the neighbouring dates.
            try:
                noon = sun.noon(obs, date=d, tzinfo=UTC)
            except ValueError:
                print(f"# {name} {ds} no solar noon, skipped")
                continue

            day = datetime.timedelta(days=1)
            rise = sett = None
            for off in (-day, datetime.timedelta(0), day):
                try:
                    r = sun.sunrise(obs, date=d + off, tzinfo=UTC)
                    if r < noon and (rise is None or r > rise):
                        rise = r
                except ValueError:
                    pass
                try:
                    s = sun.sunset(obs, date=d + off, tzinfo=UTC)
                    if s > noon and (sett is None or s < sett):
                        sett = s
                except ValueError:
                    pass

            if rise is None or sett is None:
                print(f"# {name} {ds} polar day/night, skipped")
                continue

            print(f"{name}\t{lat}\t{lon}\t{ds}\t"
                  f"{int(rise.timestamp())}\t{int(sett.timestamp())}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
